name: BundleVersion File Reviewer for PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write  # Required to add comments to PRs

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest commit SHA
        id: get_latest_commit
        run: |
          RESPONSE=$(curl -s -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits")

          HTTP_STATUS=${RESPONSE: -3}
          BODY=${RESPONSE::-3}

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to fetch latest commit. HTTP Status: $HTTP_STATUS"
            echo "Response: $BODY"
            exit 1
          fi

          LATEST_COMMIT_SHA=$(echo "$BODY" | jq -r '.[-1].sha')

          if [ -z "$LATEST_COMMIT_SHA" ]; then
            echo "Error: Could not extract commit SHA."
            exit 1
          fi

          echo "LATEST_COMMIT_SHA=$LATEST_COMMIT_SHA" >> $GITHUB_ENV
          echo "Latest commit SHA: $LATEST_COMMIT_SHA"

      - name: Get changed bundle version files
        id: get_changed_files
        run: |
          RESPONSE=$(curl -s -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")

          HTTP_STATUS=${RESPONSE: -3}
          BODY=${RESPONSE::-3}

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Failed to fetch changed files. HTTP Status: $HTTP_STATUS"
            echo "Response: $BODY"
            exit 1
          fi

          echo "$BODY" | jq -r '.[] | select((.filename | contains("/BundleVersions/")) and (.status == "added" or .status == "modified") and (.filename | capture(".*/(?<basename>[^/]+)$").basename as $name | ($name != "dev.json" and $name != "live.json"))) | .filename' > changed_files_list.txt

          if [ ! -s changed_files_list.txt ]; then
            echo "No eligible files found."
            exit 0
          fi

          echo "Filtered changed files:"
          cat changed_files_list.txt

      - name: Post PR comment
        run: |
          while IFS= read -r FILE_PATH; do
            [ -z "$FILE_PATH" ] && continue  # Skip empty lines

            COMMENT_BODY="Automated PR Review: Please delete this file."
            POSITION=1  # Set a default line position for commenting

            echo "Posting comment to: $FILE_PATH"

            RESPONSE=$(curl -s -w "%{http_code}" -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github+json" \
                 -d "{\"body\": \"$COMMENT_BODY\", \"path\": \"$FILE_PATH\", \"commit_id\": \"$LATEST_COMMIT_SHA\", \"subject_type\": \"file\", \"position\": $POSITION}" \
                 "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments")

            HTTP_STATUS=${RESPONSE: -3}
            BODY=${RESPONSE::-3}

            if [ "$HTTP_STATUS" -ne 201 ]; then
              echo "Error: Failed to post comment. HTTP Status: $HTTP_STATUS"
              echo "Response: $BODY"
              exit 1
            fi

          done < changed_files_list.txt

      - name: Cleanup temporary file
        if: always()
        run: rm -f changed_files_list.txt
